### ISSUE TITLE
RESTful API 재구성

### ISSUE THREAD

**Issue by yuta-97** [Cozy-Ho/UFO_Server#1]
현재 API를 RESTful 하게 변경하기

**Comment by yuta-97** [comment]
API 예시

GET /festival

GET /festival/:id

POST /festival

GET /festival/:id/store

//store list of some festival 
POST /festival/:id/store

GET /festival/:id/store/:id/menu

//menu list of some store 
POST /store/:id/ menu

**Comment by nrhys2005** [comment]
Sales Customer인지 확인하는 API
